version: '3.8'

services:
  cms-core:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SETTINGS_FILE=config/settings.yaml
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cms_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: